<div class="container">
    <div class="mt-8">
        <h4 class="text-danger">You need to setup your homepage first!</h4>

        <p><strong>1. Go to Admin -> Plugins then activate all plugins.</strong></p>
        <p><strong>2. Go to Admin -> Pages and create a page:</strong></p>

        <div class="mt-2">
            <div>- Content:</div>
            <pre class="my-2 bg-dark text-light p-2 rounded"><code>[hero-banner style="1" title="Crafting Intuitive <span class='text-primary'>Digital Experiences</span>" subtitle="👋 Hi there, I'm William" description="I assist individuals and brands in achieving their objectives by creating and developing user-focused digital products and interactive experiences." below_button_text="+ 12 years with professional design software" primary_button_text="Download CV" primary_button_link="/storage/main/resume/cv.pdf" primary_button_icon="ti ti-download" secondary_button_text="Hire Me" secondary_button_link="#contact" secondary_button_icon="ti ti-arrow-right" quantity="6" name_1="Figma" image_1="main/skills/1.png" name_2="Adobe XD" image_2="main/skills/2.png" name_3="Illustrator" image_3="main/skills/3.png" name_4="Sketch" image_4="main/skills/4.png" name_5="Photoshop" image_5="main/skills/5.png" name_6="Webflow" image_6="main/skills/6.png" background_image="main/general/hero-bg.png" right_image="main/general/hero-man.png" right_image_shape="main/general/hero-decorate.png" enable_lazy_loading="no"][/hero-banner]
                [stats-counter style="1" quantity="4" label_1="Years of" highlight_text_1="Experience" count_1="12" label_2="Projects" highlight_text_2="Completed" count_2="250" label_3="Satisfied" highlight_text_3="Happy Clients" count_3="680" label_4="Awards" highlight_text_4="Won Received" count_4="18" enable_lazy_loading="no"][/stats-counter]
                [services style="1" title="What do I offer?" subtitle="My journey started with a fascination for design and technology, leading me to specialize in UI/UX design" service_ids="4,1,2,3" enable_lazy_loading="yes"][/services]
                [projects style="1" title="My Latest Works" subtitle="I believe that working hard and trying to learn every day will <br> make me improve in satisfying my customers." project_ids="1,2,3,4" bottom_action_text="View all" bottom_action_link="/projects" enable_lazy_loading="yes"][/projects]
                [resume style="1" title="My Resume" subtitle="I believe that working hard and trying to learn every day will <br> make me improve in satisfying my customers." action_text="Get in touch" action_link="#contact" resume_1_title="Education" resume_1_title_icon="ti ti-school" resume_1_quantity="4" resume_1_time_1="2018 - 2019" resume_1_title_1="Certification in UX Design" resume_1_description_1="University of Stanford" resume_1_subtitle_1="4.9/5" resume_1_time_2="2017 - 2018" resume_1_title_2="Certification in Web Dev" resume_1_description_2="University of Stanford" resume_1_subtitle_2="5.0/5" resume_1_time_3="2014 - 2016" resume_1_title_3="Advanced UX/UI Bootcamp" resume_1_description_3="Design Academy" resume_1_subtitle_3="4.9/5" resume_1_time_4="2012 - 2013" resume_1_title_4="Certification in Graphic Design" resume_1_description_4="Coursera" resume_1_subtitle_4="4.8/5" resume_2_title="Experience" resume_2_title_icon="ti ti-stars" resume_2_quantity="4" resume_2_time_1="2019 - Present" resume_2_title_1="Senior UI/UX Designer" resume_2_description_1="Leader in Creative team" resume_2_time_2="2016 - 2019" resume_2_title_2="UI/UX Designer" resume_2_description_2="Tech Startup" resume_2_time_3="2014 - 2016" resume_2_title_3="Freelance UI/UX Designer" resume_2_description_3="Self-Employed" resume_2_time_4="2012 - 2014" resume_2_title_4="Junior UI Designer" resume_2_description_4="Web Solutions team" bottom_text="Branding . Marketing . User Interface" background_image="main/general/grid-bg.png" enable_lazy_loading="yes"][/resume]
                [skills style="1" title="My Skills" subtitle="I thrive on turning complex problems into simple, beautiful <br> solutions that enhance user satisfaction." quantity="7" name_1="Figma" image_1="main/skills/1.png" level_1="82%" name_2="Adobe XD" image_2="main/skills/2.png" level_2="70%" name_3="Illustrator" image_3="main/skills/3.png" level_3="86%" name_4="Sketch" image_4="main/skills/4.png" level_4="81%" name_5="Photoshop" image_5="main/skills/5.png" level_5="76%" name_6="Webflow" image_6="main/skills/6.png" level_6="91%" name_7="Framer" image_7="main/skills/7.png" level_7="96%" extra_content="In addition, I have some programming knowledge such as: <br> <span class='fs-5 fw-bold text-dark'>HTML, CSS, Javascript, Bootstrap, TailwindCSS</span>" enable_lazy_loading="yes"][/skills]
                [image-slider title="Trusted by industry leaders" subtitle="I have collaborated with many large corporations, companies, and agencies around <br> the world in many fields of design and consulting" quantity="10" name_1="Brave" image_1="main/brands/1.png" url_1="https://Brave.com" open_in_new_tab_1="1" name_2="Circle" image_2="main/brands/2.png" url_2="https://Circle.com" open_in_new_tab_2="1" name_3="Discord" image_3="main/brands/3.png" url_3="https://Discord.com" open_in_new_tab_3="1" name_4="Google" image_4="main/brands/4.png" url_4="https://Google.com" open_in_new_tab_4="1" name_5="jump_" image_5="main/brands/5.png" url_5="https://jump.com" open_in_new_tab_5="1" name_6="Magic Eden" image_6="main/brands/6.png" url_6="https://Magic Eden.com" open_in_new_tab_6="1" name_7="MetaMask" image_7="main/brands/7.png" url_7="https://MetaMask.com" open_in_new_tab_7="1" name_8="Shopify" image_8="main/brands/8.png" url_8="https://Shopify.com" open_in_new_tab_8="1" name_9="Stripe" image_9="main/brands/9.png" url_9="https://Stripe.com" open_in_new_tab_9="1" name_10="Lolliapaloza" image_10="main/brands/10.png" url_10="https://Lolliapaloza.com" open_in_new_tab_10="1" enable_lazy_loading="yes"][/image-slider]
                [testimonials title="Client's Testimonials" subtitle="I believe that working hard and trying to learn every day will make me <br> improve in satisfying my customers." testimonial_ids="1,2,3,4" shape_image="main/avatars/man.png" enable_lazy_loading="yes"][/testimonials]
                [blog-posts style="1" paginate="3" title="Recent blog" subtitle="Explore the insights and trends shaping our industry" action_text="View more" action_link="/blog" enable_lazy_loading="yes"][/blog-posts]
                [contact-form style="1" display_fields="phone,email,subject,address" mandatory_fields="email,subject" title="Get in touch" subtitle="I'm always excited to take on new projects and collaborate with innovative minds. If you <br> have a project in mind or just want to chat about design, feel free to reach out!" quantity="4" label_1="Phone" content_1="+1-234-567-8901" icon_1="ti ti-phone" url_1="tel:+1-234-567-8901" label_2="Email" content_2="contact@botble.com" icon_2="ti ti-mail" url_2="mailto:contact@botble.com" label_3="X (Twitter)" content_3="Botble Technologies" icon_3="ti ti-user" url_3="https://x.com/botble" label_4="Address" content_4="0811 Erdman Prairie, Joaville CA" icon_4="ti ti-map" url_4="https://google.com/maps"][/contact-form]
                </code></pre>
            <br>
            <div>- Template: <strong>Default</strong>.</div>
        </div>

        <p><strong>3. Then go to Admin -> Appearance -> Theme options -> Page to set your homepage.</strong></p>
    </div>
</div>
